---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bodymindarts/docker-machine-setup}


params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  AWS_BUCKET:
  MACHINE_NAME: delmo-pipeline-machine

run:
  path: /setup-aws
