---
groups:
- name: delmo
  jobs: [test-master, test-all, end-to-end]
- name: images
  jobs: [build-task-image, build-docker-machine-setup]
- name: docker-machine
  jobs: [provision-docker-host]

jobs:
- name: test-master
  plan:
  - aggregate:
    - {get: delmo, trigger: true}
    - get: delmo-ci
  - task: run-tests
    file: delmo-ci/ci/tasks/run-tests.yml

- name: test-all
  plan:
  - aggregate:
    - {get: delmo-all, trigger: true}
  - task: run-tests-all
    file: delmo-all/ci/tasks/run-tests-all.yml

- name: end-to-end
  serial: true
  plan:
  - get: delmo-ci
  - {get: delmo, trigger: true, passed: [test-master]}
  - task: end-to-end-test
    file: delmo-ci/ci/tasks/end-to-end-test.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_REGION: {{aws_region}}
      AWS_BUCKET: {{aws_bucket}}

- name: provision-docker-host
  serial: true
  plan:
  - get: delmo-ci
  - task: provision-docker-host
    file: delmo-ci/ci/tasks/provision-docker-host.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_REGION: {{aws_region}}
      AWS_BUCKET: {{aws_bucket}}

- name: build-task-image
  serial: true
  plan:
    - {get: pipeline-ci-image, trigger: true}
    - put: docker-image-ci
      params:
        build: pipeline-ci-image/ci/ci_image

- name: build-docker-machine-setup
  serial: true
  plan:
    - {get: docker-machine-setup, trigger: true}
    - put: docker-machine-setup-image
      params:
        build: docker-machine-setup-build/images/docker-machine-setup

resources:

- name: delmo-ci
  type: git
  source:
    uri: https://github.com/bodymindarts/delmo
    branch: {{pipeline-branch}}

- name: delmo
  type: git
  source:
    uri: https://github.com/bodymindarts/delmo
    branch: {{pipeline-branch}}

- name: delmo-all
  type: git-multibranch
  source:
    uri: https://github.com/bodymindarts/delmo
    branches: '.*'
    ignore_branches: 'master'

- name: pipeline-ci-image
  type: git
  source:
    uri: https://github.com/bodymindarts/delmo
    branch: {{pipeline-branch}}
    paths: [ci/ci_image/*]

- name: docker-image-ci
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: bodymindarts/delmo-pipeline

- name: docker-machine-setup
  type: git
  source:
    uri: https://github.com/bodymindarts/delmo
    branch: {{pipeline-branch}}
    paths: [images/docker-machine-setup/*]

- name: docker-machine-setup-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: bodymindarts/docker-machine-setup

resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource
